# Generated by Django 3.2.16 on 2022-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for review'), ('accepted', 'Accepted'), ('done', 'Done'), ('rejected', 'Rejected')], default='status_pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='idea',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
